### ISSUE TITLE
v3 Launch to-do list

### ISSUE THREAD

**Issue by roginfarrer** [roginfarrer/react-collapsed#50]
* [x] Update readme to reflect `latest` instead of `next`
* [x] Write release notes -- what's new
* [x] Blog post on 1) measuring element with and without `box-sizing: border-box`, or 2) adopting TypeScript
